import AdminNvar from '@/app/ui/Nvar/adminNvar';
//import "./globals.css";
import FooterComponent from '@/app/ui/footer/footer_component';
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <AdminNvar></AdminNvar>
                {children}
                <FooterComponent></FooterComponent>
            </body>
        </html>
    )
}
